version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    environment:
      NODE_ENV: development
      ORIGIN: http://localhost:4000
      PORT: 4000
      ACTUAL_PERIOD: 202010
      SECRET: E8D94B8BE8AE1
      SCRAPER_BASE_URL: https://guayacan.uninorte.edu.co/4PL1CACI0N35/registro
      DATABASE_URL: mongodb://linku_user:root_12345@db:27017/linku
      REDIS_URL: redis://redis:6379
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - db
      - redis
  db:
    image: mongo
    volumes:
      - mongo-data:/data
      # - ./db/dump:/dump
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: linku_user
      MONGO_INITDB_ROOT_PASSWORD: root_12345
      MONGO_INITDB_DATABASE: linku
    ports:
      - 27017:27017
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always

volumes:
  mongo-data: ~
  redis-data: ~